# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('check_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
